### ISSUE TITLE
levels.lmp not loading.

### ISSUE THREAD

**Issue by eGax** [victorbstan/menusys#1]
Running under Manjaro Linux KDE using latest qss Linux (amd64) | 2021-June-25 release in a clean install of Quake. The levels.lmp is not loading from inside the `menu.pak/menugfx/levels.lmp`

![image](https://user-images.githubusercontent.com/9817245/123900308-daf6c980-d936-11eb-8a4f-f6d228480930.png)
I could find nothing wrong with the lmp. Just by extracting it from the menu.pak and putting it in `/id1/menugfx/levels.lmp` menusys then loads the levels.lmp just fine.

**Comment by victorbstan** [comment]
new release has updated paths.

**Comment by eGax** [comment]
Fixed
