### ISSUE TITLE
Crashing to desktop when Options is clicked on.

### ISSUE THREAD

**Issue by eGax** [victorbstan/menusys#2]
Running under Manjaro Linux KDE using latest qss Linux (amd64) | 2021-June-25 release in a clean install of Quake. Load qss, click on Options, qss crashes to desktop with : `QUAKE ERROR: R_RenderView: NULL worldmodel`

If I load a map 1st, open menu, and then click Options the options menu page opens and behaves fine as intended.

**Comment by victorbstan** [comment]
removed 3d model in new release, to prevent crashing
