### ISSUE TITLE
autoexec.cfg has mixed case windows only cvar.

### ISSUE THREAD

**Issue by eGax** [victorbstan/menusys#3]
Running under Manjaro Linux KDE using latest qss Linux (amd64) | 2021-June-25 release in a clean install of Quake. Unless your intended target for your menusys is windows only mixed case cvars are a no-go on Linux. They will be reported as Unknown commands. 

Line 13 ```GL_texturemode GL_Nearest``` of autoexec.cfg returns ```Unknown command "GL_texturemode"``` in the quake console.

There is no need to capitalize any part of it so for compatibility sake it should be all lower case: ```gl_texturemode gl_nearest```

Thanks.

**Comment by victorbstan** [comment]
fixed in new release
