### ISSUE TITLE
mod not recognized if dot in name (apparently)

### ISSUE THREAD

**Issue by neogeographica** [victorbstan/menusys#4]
For example, "smej2" will show up in the Levels menu for me, but "smej2_1.1" will not.

**Comment by eGax** [comment]
I can confirm this in Linux or Windows.

**Comment by victorbstan** [comment]
New beta release for this issue: https://github.com/victorbstan/menusys/releases/tag/v1.0-beta.3

**Comment by neogeographica** [comment]
Fix confirmed here.
